name: unitest

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/xmake.yml"
      - "src/**"
      - "tests/**"
      - "api/**"
      - "xmake.lua"
      - "pixi.toml"

  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/xmake.yml"
      - "src/**"
      - "tests/**"
      - "api/**"
      - "xmake.lua"
      - "pixi.toml"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.os }}
      cancel-in-progress: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: ${{ matrix.os }}
          package-cache: true
          package-cache-key: ${{ matrix.os }}-pixi

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.61.0
          activate-environment: true
          cache: true
          locked: true
          environments: dev

      - name: Build (debug)
        run: |
          pixi run ci-build debug

      - name: Build (release)
        run: |
          pixi run ci-build release
